
services:
  app:
    build: .
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev_party_db

    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - my-network
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Mount local timezone config

  postgres:
    image: postgres:13
    container_name: dev-postgres
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_party_db
      TZ: Europe/London  # Set container timezone to BST
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:

